-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "gstApplicable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "gstRate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "invoiceType" TEXT NOT NULL DEFAULT 'regular';
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "isInterState" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "cgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "sgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "igstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "cgstRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "sgstRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "igstRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "cgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "sgstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "sale_items" ADD COLUMN IF NOT EXISTS "igstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
